name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: LeetCode Sync
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
